"""added a login session table

Revision ID: 6b6af71a2b07
Revises: 
Create Date: 2024-09-16 11:49:26.043161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6af71a2b07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loginSession', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('session_token', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('login_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('logout_time', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loginSession', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('logout_time')
        batch_op.drop_column('login_time')
        batch_op.drop_column('session_token')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
